# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_remote_indigenous_uploader', '0003_auto_20170210_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingremoteindigenousdata',
            name='target_new_houses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housingremoteindigenousdata',
            name='target_refurbishments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingremoteindigenousdata',
            name='new_houses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingremoteindigenousdata',
            name='refurbishments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
