# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_remote_indigenous_uploader', '0004_auto_20180529_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingremoteindigenousdata',
            name='target_new_houses',
        ),
        migrations.RemoveField(
            model_name='housingremoteindigenousdata',
            name='target_refurbishments',
        ),
        migrations.AlterField(
            model_name='housingremoteindigenousdata',
            name='new_houses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housingremoteindigenousdata',
            name='refurbishments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
