# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0092_auto_20180502_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetfamily',
            name='subtitle',
            field=models.CharField(blank=True, help_text=b'The option subheading of widgets in this family. May be parametised.', max_length=240, null=True),
        ),
    ]
