# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0093_auto_20180808_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdataset',
            name='label',
            field=models.CharField(help_text=b'A longer human-readable description of the dataset. (May be parametised)', max_length=128, verbose_name=b'name'),
        ),
    ]
