# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_npa_uploader', '0004_auto_20170210_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructurekeyprojects',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'In progress'), (3, 'Not due to commence'), (4, 'Not completed and past agreed timeframe'), (5, 'Not applicable'), (6, 'Cancelled')]),
        ),
    ]
