# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_ecenqs_uploader', '0003_auto_20170210_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationecenqsdata',
            name='sig_improvement_req',
            field=models.DecimalField(decimal_places=0, default='0.0', max_digits=6),
        ),
    ]
