# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_homelessness_npa_uploader', '0007_auto_20170210_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housinghomelessnessnpaprogress',
            name='plan2',
        ),
    ]
